version: "3"
services:
  read-db:
    image: mongo:latest
    container_name: read-db
    hostname: read-db
    volumes:
        - ./conf/db/home/mongodb/:/home/mongodb
        - ./conf/db/mongod.conf:/etc/mongod.conf
        - ./conf/db/initdb.d/:/docker-entrypoint-initdb.d/
        - ./mongodb/data/db/:/data/db/
    env_file:
        - .env
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
        - "27017:27017"
    command: ["-f", "/etc/mongod.conf"]
